#!/usr/bin/env python3
"""
═══════════════════════════════════════════════════════════════════════════════
Variant Analysis Code Library — H9 T2T Diploid ASE Project
═══════════════════════════════════════════════════════════════════════════════

Reusable functions for:
  1. Loading variant catalogs (from haplotype alignment CSVs)
  2. Coordinate conversion (relative ↔ absolute haplotype coordinates)
  3. ASE read counting from .ase.bam files (UCSC-generated)
  4. Sequence extraction for Evo2 analysis
  5. Gene-level ASE summary and verification
  6. Filtering and subsetting variants

Project context:
  - H9 human embryonic stem cell line, T2T diploid assembly (t2t_h9_v01)
  - Cell types: iPSC, FPP, astrocyte, microglia
  - Genes: SNCA, HTT, LRRK2, GBA1, SMN1, SMN2
  - .ase.bam files generated by UCSC Genome Server Group

Usage:
  from variant_analysis_library import *
  # or import individual functions

Author: Shruti Patil
"""

import os
import csv
import subprocess
from collections import defaultdict

# ════════════════════════════════════════════════════════════════════════════
# PATHS & CONSTANTS
# ════════════════════════════════════════════════════════════════════════════
BASE      = os.path.expanduser('~/reganalysis')
ASE_DIR   = os.path.join(BASE, 'ase')
GENOMES   = os.path.join(BASE, 'genomes')
RESULTS   = os.path.join(BASE, 'results')
ASE_V2    = os.path.join(BASE, 'ase_v2')
SAMTOOLS  = '/opt/homebrew/bin/samtools'

# Reference genomes
HG38_REF    = os.path.join(GENOMES, 'hg38.fa')
HAP1_REF    = os.path.join(GENOMES, 't2t_h9_v01_hap1.fa')
HAP2_REF    = os.path.join(GENOMES, 't2t_h9_v01_hap2.fa')

# Cell types available in .ase.bam files
CELLTYPES = ['iPSC', 'FPP', 'astrocyte', 'microglia']

# Evo2 flanking size
FLANK = 512  # ±512 bp for ~1024 bp input sequences

# ════════════════════════════════════════════════════════════════════════════
# GENE CONFIGURATION
# ════════════════════════════════════════════════════════════════════════════
# Coordinates from CAT GTF annotations (H9_HAP1.gtf, H9_HAP2.gtf)
# fasta_start = gene_body_start - 500000 (all extractions used ±500kb from TSS)
# Variant files from direct haplotype-to-haplotype alignment

GENES_CONFIG = {
    'SNCA': {
        'variant_file': os.path.join(RESULTS, 'SNCA_variants_aligned.csv'),
        'hap1_chrom':       'chr4_hap1',
        'hap2_chrom':       'chr4_hap2',
        'hg38_chrom':       'chr4',
        'fasta_start_hap1': 92201524,               # 92701524 - 500000
        'fasta_start_hap2': 90111547,               # 90611547 - 500000
        'gene_body_hap1':   (92701524, 92810571),
        'gene_body_hap2':   (90611547, 90749628),
        'expected_variants': 832,
        'has_gene_col': False,
    },
    'HTT': {
        'variant_file': os.path.join(RESULTS, 'haplotype_variants_aligned.csv'),
        'hap1_chrom':       'chr4_hap1',
        'hap2_chrom':       'chr4_hap2',
        'hg38_chrom':       'chr4',
        'fasta_start_hap1': 2551762,                # 3051762 - 500000
        'fasta_start_hap2': 2535268,                # 3035268 - 500000
        'gene_body_hap1':   (3051762, 3254349),
        'gene_body_hap2':   (3035268, 3237826),
        'expected_variants': 918,
        'has_gene_col': True,
        'gene_filter': 'HTT',
    },
    'LRRK2': {
        'variant_file': os.path.join(RESULTS, 'haplotype_variants_aligned.csv'),
        'hap1_chrom':       'chr12_hap1',
        'hap2_chrom':       'chr12_hap2',
        'hg38_chrom':       'chr12',
        'fasta_start_hap1': 39693975,               # 40193975 - 500000
        'fasta_start_hap2': 40389815,               # 40889815 - 500000
        'gene_body_hap1':   (40193975, 40366656),
        'gene_body_hap2':   (40889815, 41062145),
        'expected_variants': 1360,
        'has_gene_col': True,
        'gene_filter': 'LRRK2',
    },
    'GBA': {
        'variant_file': os.path.join(RESULTS, 'haplotype_variants_aligned.csv'),
        'hap1_chrom':       'chr1_hap1',
        'hap2_chrom':       'chr1_hap2',
        'hg38_chrom':       'chr1',
        'fasta_start_hap1': 155897616,              # 156397616 - 500000
        'fasta_start_hap2': 148794168,              # 149294168 - 500000
        'gene_body_hap1':   (156397616, 156407863),
        'gene_body_hap2':   (149294168, 149304415),
        'expected_variants': 548,
        'has_gene_col': True,
        'gene_filter': 'GBA',
    },
    'SMN1': {
        'variant_file': os.path.join(RESULTS, 'SMN_variants_aligned.csv'),
        'hap1_chrom':       'chr5_hap1',
        'hap2_chrom':       'chr5_hap2',
        'hg38_chrom':       'chr5',
        'fasta_start_hap1': 74690828,               # 75190828 - 500000
        'fasta_start_hap2': 70957984,               # 71457984 - 500000
        'gene_body_hap1':   (75190828, 75219735),
        'gene_body_hap2':   (71457984, 71486893),
        'expected_variants': 857,
        'has_gene_col': False,
    },
}

# Gene-level ASE counts from the definitive figure data
# Format: {gene: {celltype: (hap1_reads, hap2_reads)}}
FIGURE_ASE_COUNTS = {
    'SNCA':  {'iPSC': (33,32),  'FPP': (54,52),  'astrocyte': (23,56),  'microglia': (162,154)},
    'HTT':   {'iPSC': (82,45),  'FPP': (58,53),  'astrocyte': (76,53),  'microglia': (136,88)},
    'LRRK2': {'iPSC': (0,0),    'FPP': (99,120), 'astrocyte': (5,12),   'microglia': (74,92)},
    'GBA':   {'iPSC': (0,2),    'FPP': (2,0),    'astrocyte': (1,1),    'microglia': (1,0)},
    'SMN1':  {'iPSC': (22,5),   'FPP': (23,9),   'astrocyte': (24,11),  'microglia': (15,3)},
    'SMN2':  {'iPSC': (323,0),  'FPP': (143,0),  'astrocyte': (285,0),  'microglia': (88,0)},
}

# ════════════════════════════════════════════════════════════════════════════
# 1. VARIANT LOADING
# ════════════════════════════════════════════════════════════════════════════

def load_variants(gene):
    """
    Load variants from the correct haplotype-aligned CSV for a given gene.

    Returns list of dicts with keys:
      hap1_pos_rel, hap2_pos_rel, hap1_rel (relative to TSS),
      hap1_base, hap2_base, type

    Example:
      >>> variants = load_variants('SNCA')
      >>> len(variants)
      832
    """
    if gene not in GENES_CONFIG:
        raise ValueError(f"Unknown gene: {gene}. Available: {list(GENES_CONFIG.keys())}")

    cfg = GENES_CONFIG[gene]
    path = cfg['variant_file']
    variants = []

    with open(path) as f:
        reader = csv.DictReader(f)
        for row in reader:
            # Filter by gene column if shared CSV (HTT/LRRK2/GBA)
            if cfg.get('has_gene_col') and row.get('gene') != cfg.get('gene_filter'):
                continue
            variants.append({
                'hap1_pos_rel': int(row['hap1_pos']),
                'hap2_pos_rel': int(row['hap2_pos']),
                'hap1_rel':     int(row['hap1_rel']),
                'hap1_base':    row['hap1_base'],
                'hap2_base':    row['hap2_base'],
                'type':         row['type'],
            })
    return variants


def load_all_variants():
    """Load variants for all genes. Returns dict: {gene: [variants]}."""
    return {gene: load_variants(gene) for gene in GENES_CONFIG}


# ════════════════════════════════════════════════════════════════════════════
# 2. COORDINATE CONVERSION
# ════════════════════════════════════════════════════════════════════════════

def rel_to_abs(gene, hap1_pos_rel, hap2_pos_rel):
    """
    Convert relative FASTA positions to absolute haplotype coordinates.

    Args:
      gene: gene name (SNCA, HTT, LRRK2, GBA, SMN1)
      hap1_pos_rel: position within extracted hap1 FASTA (from CSV)
      hap2_pos_rel: position within extracted hap2 FASTA (from CSV)

    Returns:
      (hap1_abs, hap2_abs) — absolute coordinates for use with .ase.bam

    Formula: abs = fasta_start + rel_pos
    Where fasta_start = gene_TSS - 500000
    """
    cfg = GENES_CONFIG[gene]
    h1_abs = cfg['fasta_start_hap1'] + hap1_pos_rel
    h2_abs = cfg['fasta_start_hap2'] + hap2_pos_rel
    return h1_abs, h2_abs


def is_in_gene_body(gene, hap1_abs, hap2_abs):
    """
    Check if a variant falls within the gene body on either haplotype.

    Uses gene body coordinates from CAT GTF annotations.
    """
    cfg = GENES_CONFIG[gene]
    gb_h1 = cfg['gene_body_hap1']
    gb_h2 = cfg['gene_body_hap2']
    return (gb_h1[0] <= hap1_abs <= gb_h1[1]) or \
           (gb_h2[0] <= hap2_abs <= gb_h2[1])


def variant_distance_to_tss(gene, hap1_rel):
    """
    Return distance from variant to gene TSS.
    Negative = upstream, positive = downstream (within gene body).

    The hap1_rel column in variant CSVs is already this value.
    """
    return hap1_rel


# ════════════════════════════════════════════════════════════════════════════
# 3. ASE READ COUNTING
# ════════════════════════════════════════════════════════════════════════════

def get_ase_bam_path(haplotype, celltype):
    """
    Get path to the .ase.bam file for a given haplotype and cell type.

    Args:
      haplotype: 'hap1' or 'hap2'
      celltype:  'iPSC', 'FPP', 'astrocyte', or 'microglia'

    Returns: full path to .ase.bam file
    """
    return os.path.join(ASE_DIR,
        f't2t_h9_v01_{haplotype}.H9-02-ES-001_{celltype}.ase.bam')


def count_reads_at_position(bam_path, chrom, pos):
    """
    Count reads overlapping a single position in a BAM file.
    Uses samtools view -c.

    Returns: int (read count)
    """
    region = f"{chrom}:{pos}-{pos}"
    try:
        result = subprocess.run(
            [SAMTOOLS, 'view', '-c', bam_path, region],
            capture_output=True, text=True, timeout=10
        )
        return int(result.stdout.strip()) if result.returncode == 0 else 0
    except Exception:
        return 0


def count_ase_reads(gene, hap1_abs, hap2_abs, celltype):
    """
    Count allele-specific reads at a variant position for one cell type.

    Args:
      gene:     gene name
      hap1_abs: absolute hap1 coordinate
      hap2_abs: absolute hap2 coordinate
      celltype: cell type name

    Returns: (hap1_reads, hap2_reads)
    """
    cfg = GENES_CONFIG[gene]
    h1_bam = get_ase_bam_path('hap1', celltype)
    h2_bam = get_ase_bam_path('hap2', celltype)
    h1_reads = count_reads_at_position(h1_bam, cfg['hap1_chrom'], hap1_abs)
    h2_reads = count_reads_at_position(h2_bam, cfg['hap2_chrom'], hap2_abs)
    return h1_reads, h2_reads


def count_ase_all_celltypes(gene, hap1_abs, hap2_abs):
    """
    Count ASE reads across all 4 cell types.

    Returns: dict {celltype: (hap1_reads, hap2_reads)}
    """
    return {ct: count_ase_reads(gene, hap1_abs, hap2_abs, ct) for ct in CELLTYPES}


def count_gene_level_ase(gene, celltype):
    """
    Count total gene-level ASE reads (as done in Figure 3).
    Uses `samtools view -c` on the entire gene body region.

    Returns: (hap1_total, hap2_total)
    """
    cfg = GENES_CONFIG[gene]
    gb_h1 = cfg['gene_body_hap1']
    gb_h2 = cfg['gene_body_hap2']

    h1_bam = get_ase_bam_path('hap1', celltype)
    h2_bam = get_ase_bam_path('hap2', celltype)

    h1_region = f"{cfg['hap1_chrom']}:{gb_h1[0]}-{gb_h1[1]}"
    h2_region = f"{cfg['hap2_chrom']}:{gb_h2[0]}-{gb_h2[1]}"

    try:
        r1 = subprocess.run([SAMTOOLS, 'view', '-c', h1_bam, h1_region],
                            capture_output=True, text=True, timeout=10)
        h1 = int(r1.stdout.strip()) if r1.returncode == 0 else 0
    except Exception:
        h1 = 0

    try:
        r2 = subprocess.run([SAMTOOLS, 'view', '-c', h2_bam, h2_region],
                            capture_output=True, text=True, timeout=10)
        h2 = int(r2.stdout.strip()) if r2.returncode == 0 else 0
    except Exception:
        h2 = 0

    return h1, h2


# ════════════════════════════════════════════════════════════════════════════
# 4. SEQUENCE EXTRACTION (for Evo2)
# ════════════════════════════════════════════════════════════════════════════

def fetch_haplotype_sequence(haplotype, chrom, start, end):
    """
    Fetch sequence from a haplotype reference FASTA.

    Args:
      haplotype: 'hap1' or 'hap2'
      chrom: chromosome name (e.g., 'chr4_hap1')
      start, end: 1-based coordinates

    Returns: uppercase DNA sequence string
    """
    ref_fa = HAP1_REF if haplotype == 'hap1' else HAP2_REF
    region = f"{chrom}:{start}-{end}"
    try:
        result = subprocess.run(
            [SAMTOOLS, 'faidx', ref_fa, region],
            capture_output=True, text=True, timeout=10
        )
        if result.returncode != 0:
            return ''
        return ''.join(result.stdout.strip().split('\n')[1:]).upper()
    except Exception:
        return ''


def fetch_hg38_sequence(chrom, start, end):
    """Fetch sequence from hg38 reference."""
    region = f"{chrom}:{start}-{end}"
    try:
        result = subprocess.run(
            [SAMTOOLS, 'faidx', HG38_REF, region],
            capture_output=True, text=True, timeout=10
        )
        if result.returncode != 0:
            return ''
        return ''.join(result.stdout.strip().split('\n')[1:]).upper()
    except Exception:
        return ''


def make_evo2_sequences(gene, hap1_abs, hap1_base, hap2_base, variant_type,
                        flank=FLANK):
    """
    Extract ref and alt sequences for Evo2 scoring.

    For SNVs: extracts ±flank bp around the variant from hap1 reference,
    then substitutes the alt (hap2) base at center.

    Args:
      gene:         gene name
      hap1_abs:     absolute hap1 coordinate
      hap1_base:    reference allele (hap1)
      hap2_base:    alternate allele (hap2)
      variant_type: 'SNV', 'INS(Nbp)', 'DEL(Nbp)', etc.
      flank:        flanking bp (default 512)

    Returns: (ref_seq, alt_seq) — each ~1024 bp
    """
    if variant_type != 'SNV' or len(hap1_base) != 1 or len(hap2_base) != 1:
        return '', ''

    cfg = GENES_CONFIG[gene]
    h1_chrom = cfg['hap1_chrom']

    ref_seq = fetch_haplotype_sequence(
        'hap1', h1_chrom,
        max(1, hap1_abs - flank),
        hap1_abs + flank
    )
    if not ref_seq:
        return '', ''

    # Alt sequence: substitute variant base at center position
    offset = flank  # variant is at center
    alt_seq = ref_seq[:offset] + hap2_base.upper() + ref_seq[offset + 1:]

    return ref_seq, alt_seq


# ════════════════════════════════════════════════════════════════════════════
# 5. GENE-LEVEL SUMMARY & VERIFICATION
# ════════════════════════════════════════════════════════════════════════════

def summarize_gene(gene, variants=None):
    """
    Print summary stats for a gene: variant counts, types, gene body overlap.

    Args:
      gene: gene name
      variants: optional pre-loaded variant list (loads if None)
    """
    if variants is None:
        variants = load_variants(gene)

    cfg = GENES_CONFIG[gene]
    snvs = [v for v in variants if v['type'] == 'SNV']
    indels = [v for v in variants if v['type'] != 'SNV']

    # Count in gene body
    in_body = 0
    for v in variants:
        h1_abs, h2_abs = rel_to_abs(gene, v['hap1_pos_rel'], v['hap2_pos_rel'])
        if is_in_gene_body(gene, h1_abs, h2_abs):
            in_body += 1

    print(f"{gene}:")
    print(f"  Total variants:  {len(variants)} (expected {cfg['expected_variants']})")
    print(f"  SNVs:            {len(snvs)}")
    print(f"  Indels:          {len(indels)}")
    print(f"  In gene body:    {in_body}")


def verify_gene_level_ase(gene, celltype='astrocyte'):
    """
    Verify gene-level ASE counts match the figure's published values.

    Returns: (computed_h1, computed_h2, figure_h1, figure_h2, match)
    """
    h1, h2 = count_gene_level_ase(gene, celltype)
    fig_h1, fig_h2 = FIGURE_ASE_COUNTS[gene][celltype]
    match = (h1 == fig_h1 and h2 == fig_h2)
    print(f"{gene} {celltype}: computed H1={h1} H2={h2} | "
          f"figure H1={fig_h1} H2={fig_h2} | "
          f"{'MATCH' if match else 'MISMATCH'}")
    return h1, h2, fig_h1, fig_h2, match


# ════════════════════════════════════════════════════════════════════════════
# 6. FILTERING & SUBSETTING
# ════════════════════════════════════════════════════════════════════════════

def filter_snvs(variants):
    """Return only SNV variants."""
    return [v for v in variants if v['type'] == 'SNV']


def filter_gene_body(gene, variants):
    """Return only variants within the gene body."""
    return [
        v for v in variants
        if is_in_gene_body(gene, *rel_to_abs(gene, v['hap1_pos_rel'], v['hap2_pos_rel']))
    ]


def filter_by_region(gene, variants, upstream_bp=0, downstream_bp=0):
    """
    Filter variants by distance to TSS.

    Args:
      upstream_bp:   include variants up to N bp upstream of TSS (negative hap1_rel)
      downstream_bp: include variants up to N bp downstream of TSS (positive hap1_rel)

    Example: filter_by_region('SNCA', variants, upstream_bp=5000, downstream_bp=0)
             → variants within 5kb upstream of SNCA TSS
    """
    return [
        v for v in variants
        if -upstream_bp <= v['hap1_rel'] <= downstream_bp
    ]


def filter_with_ase_reads(gene, variants, celltype='astrocyte', min_reads=1):
    """
    Filter to variants that have at least min_reads total ASE reads.
    WARNING: This calls samtools for each variant — can be slow.
    """
    result = []
    for v in variants:
        h1_abs, h2_abs = rel_to_abs(gene, v['hap1_pos_rel'], v['hap2_pos_rel'])
        h1r, h2r = count_ase_reads(gene, h1_abs, h2_abs, celltype)
        if h1r + h2r >= min_reads:
            v_copy = dict(v)
            v_copy['hap1_reads'] = h1r
            v_copy['hap2_reads'] = h2r
            result.append(v_copy)
    return result


# ════════════════════════════════════════════════════════════════════════════
# 7. OUTPUT CATALOG GENERATION
# ════════════════════════════════════════════════════════════════════════════

def load_catalog(path=None):
    """
    Load the full variant catalog CSV.

    Default path: ase_v2/all_variants_astrocyte_ase_evo2.csv
    """
    if path is None:
        path = os.path.join(ASE_V2, 'all_variants_astrocyte_ase_evo2.csv')

    rows = []
    with open(path) as f:
        reader = csv.DictReader(f)
        for row in reader:
            # Convert numeric fields
            for key in ['hap1_abs_pos', 'hap2_abs_pos', 'hap1_rel_to_tss',
                        'astro_hap1_reads', 'astro_hap2_reads',
                        'iPSC_hap1_reads', 'iPSC_hap2_reads',
                        'FPP_hap1_reads', 'FPP_hap2_reads',
                        'micro_hap1_reads', 'micro_hap2_reads']:
                if key in row and row[key]:
                    row[key] = int(row[key])
            rows.append(row)
    return rows


# ════════════════════════════════════════════════════════════════════════════
# 8. QUICK REFERENCE — KEY FILE PATHS
# ════════════════════════════════════════════════════════════════════════════

FILE_PATHS = {
    'variant_catalog':       os.path.join(ASE_V2, 'all_variants_astrocyte_ase_evo2.csv'),
    'gene_level_ase':        os.path.join(ASE_V2, 'ase_all_genes_complete.csv'),
    'gene_level_counts_tsv': os.path.join(ASE_V2, 'ase_all_genes_counts.tsv'),
    'figure':                os.path.join(ASE_V2, 'Fig3_ASE_combined.png'),
    'figure_notebook':       os.path.join(BASE, 'results/figures_v3/FInal_figure.ipynb'),
    'snca_variants':         os.path.join(RESULTS, 'SNCA_variants_aligned.csv'),
    'htt_lrrk2_gba_variants': os.path.join(RESULTS, 'haplotype_variants_aligned.csv'),
    'smn_variants':          os.path.join(RESULTS, 'SMN_variants_aligned.csv'),
    'hap1_gtf':              os.path.join(BASE, 'annotations/H9_HAP1.gtf'),
    'hap2_gtf':              os.path.join(BASE, 'annotations/H9_HAP2.gtf'),
}


# ════════════════════════════════════════════════════════════════════════════
# MAIN — Run as script for quick verification
# ════════════════════════════════════════════════════════════════════════════

if __name__ == '__main__':
    print("H9 T2T Diploid Variant Analysis Library")
    print("=" * 60)
    print()

    # Show variant counts
    print("Variant counts from haplotype alignment files:")
    total = 0
    for gene in GENES_CONFIG:
        variants = load_variants(gene)
        total += len(variants)
        summarize_gene(gene, variants)
        print()

    print(f"Total variants across all genes: {total}")
    print()

    # Verify gene-level ASE
    print("Gene-level ASE verification (astrocyte):")
    print("-" * 50)
    for gene in GENES_CONFIG:
        verify_gene_level_ase(gene, 'astrocyte')
