#!/usr/bin/env python3
"""
Variant catalog v3 — Uses the REAL variant files from direct hap1-vs-hap2 alignment.

Source files (ground truth):
  SNCA:  results/SNCA_variants_aligned.csv       (832 variants)
  HTT:   results/haplotype_variants_aligned.csv   (918 variants)
  LRRK2: results/haplotype_variants_aligned.csv   (1360 variants)
  GBA:   results/haplotype_variants_aligned.csv   (548 variants)
  SMN:   results/SMN_variants_aligned.csv         (857 variants)

ASE reads: .ase.bam files generated by UCSC Genome Server Group
  (downloaded and aligned locally)

Coordinate conversion:
  All extraction regions use ±500kb from gene TSS.
  absolute_hap1_pos = fasta_start_hap1 + hap1_pos
  absolute_hap2_pos = fasta_start_hap2 + hap2_pos
"""

import os
import csv
import subprocess
from collections import defaultdict

BASE     = os.path.expanduser('~/reganalysis')
ASE_DIR  = os.path.join(BASE, 'ase')
HG38_REF = os.path.join(BASE, 'genomes/hg38.fa')
SAMTOOLS = '/opt/homebrew/bin/samtools'
OUT_CSV  = os.path.join(BASE, 'ase_v2/all_variants_astrocyte_ase_evo2.csv')
FLANK    = 512  # for Evo2 sequences

# ════════════════════════════════════════════════════════════════
# GENE COORDINATES (from CAT GTF annotations)
# fasta_start = gene_TSS - 500000 (all extractions used ±500kb)
# ════════════════════════════════════════════════════════════════
GENES_CONFIG = {
    'SNCA': {
        'variant_file': 'results/SNCA_variants_aligned.csv',
        'hap1_chrom': 'chr4_hap1',
        'hap2_chrom': 'chr4_hap2',
        'fasta_start_hap1': 92201524,   # 92701524 - 500000
        'fasta_start_hap2': 90111547,   # 90611547 - 500000
        'gene_body_hap1': (92701524, 92810571),
        'gene_body_hap2': (90611547, 90749628),
        'hg38_chrom': 'chr4',
        # Columns: hap1_rel,hap1_base,hap2_base,type,hap1_pos,hap2_pos
        'col_hap1_pos': 'hap1_pos',
        'col_hap2_pos': 'hap2_pos',
        'col_hap1_base': 'hap1_base',
        'col_hap2_base': 'hap2_base',
        'col_type': 'type',
        'col_hap1_rel': 'hap1_rel',
        'has_gene_col': False,
    },
    'HTT': {
        'variant_file': 'results/haplotype_variants_aligned.csv',
        'hap1_chrom': 'chr4_hap1',
        'hap2_chrom': 'chr4_hap2',
        'fasta_start_hap1': 2551762,    # 3051762 - 500000
        'fasta_start_hap2': 2535268,    # 3035268 - 500000
        'gene_body_hap1': (3051762, 3254349),
        'gene_body_hap2': (3035268, 3237826),
        'hg38_chrom': 'chr4',
        'col_hap1_pos': 'hap1_pos',
        'col_hap2_pos': 'hap2_pos',
        'col_hap1_base': 'hap1_base',
        'col_hap2_base': 'hap2_base',
        'col_type': 'type',
        'col_hap1_rel': 'hap1_rel',
        'has_gene_col': True,
        'gene_filter': 'HTT',
    },
    'LRRK2': {
        'variant_file': 'results/haplotype_variants_aligned.csv',
        'hap1_chrom': 'chr12_hap1',
        'hap2_chrom': 'chr12_hap2',
        'fasta_start_hap1': 39693975,   # 40193975 - 500000
        'fasta_start_hap2': 40389815,   # 40889815 - 500000
        'gene_body_hap1': (40193975, 40366656),
        'gene_body_hap2': (40889815, 41062145),
        'hg38_chrom': 'chr12',
        'col_hap1_pos': 'hap1_pos',
        'col_hap2_pos': 'hap2_pos',
        'col_hap1_base': 'hap1_base',
        'col_hap2_base': 'hap2_base',
        'col_type': 'type',
        'col_hap1_rel': 'hap1_rel',
        'has_gene_col': True,
        'gene_filter': 'LRRK2',
    },
    'GBA': {
        'variant_file': 'results/haplotype_variants_aligned.csv',
        'hap1_chrom': 'chr1_hap1',
        'hap2_chrom': 'chr1_hap2',
        'fasta_start_hap1': 155897616,  # 156397616 - 500000
        'fasta_start_hap2': 148794168,  # 149294168 - 500000
        'gene_body_hap1': (156397616, 156407863),
        'gene_body_hap2': (149294168, 149304415),
        'hg38_chrom': 'chr1',
        'col_hap1_pos': 'hap1_pos',
        'col_hap2_pos': 'hap2_pos',
        'col_hap1_base': 'hap1_base',
        'col_hap2_base': 'hap2_base',
        'col_type': 'type',
        'col_hap1_rel': 'hap1_rel',
        'has_gene_col': True,
        'gene_filter': 'GBA',
    },
    'SMN1': {
        'variant_file': 'results/SMN_variants_aligned.csv',
        'hap1_chrom': 'chr5_hap1',
        'hap2_chrom': 'chr5_hap2',
        'fasta_start_hap1': 74690828,   # 75190828 - 500000
        'fasta_start_hap2': 70957984,   # 71457984 - 500000
        'gene_body_hap1': (75190828, 75219735),
        'gene_body_hap2': (71457984, 71486893),
        'hg38_chrom': 'chr5',
        # Columns: hap1_pos,hap2_pos,hap1_rel,hap1_base,hap2_base,type
        'col_hap1_pos': 'hap1_pos',
        'col_hap2_pos': 'hap2_pos',
        'col_hap1_base': 'hap1_base',
        'col_hap2_base': 'hap2_base',
        'col_type': 'type',
        'col_hap1_rel': 'hap1_rel',
        'has_gene_col': False,
    },
}

# Figure's gene-level ASE counts for verification
FIGURE_COUNTS = {
    'SNCA':  {'iPSC': (33,32),  'FPP': (54,52),  'astrocyte': (23,56),  'microglia': (162,154)},
    'HTT':   {'iPSC': (82,45),  'FPP': (58,53),  'astrocyte': (76,53),  'microglia': (136,88)},
    'LRRK2': {'iPSC': (0,0),    'FPP': (99,120), 'astrocyte': (5,12),   'microglia': (74,92)},
    'GBA':   {'iPSC': (0,2),    'FPP': (2,0),    'astrocyte': (1,1),    'microglia': (1,0)},
    'SMN1':  {'iPSC': (22,5),   'FPP': (23,9),   'astrocyte': (24,11),  'microglia': (15,3)},
}

CELLTYPES = ['astrocyte', 'iPSC', 'FPP', 'microglia']


def ase_bam(hap, celltype):
    return os.path.join(ASE_DIR,
        f't2t_h9_v01_{hap}.H9-02-ES-001_{celltype}.ase.bam')


def count_reads_at_pos(bam_path, chrom, pos):
    """Count reads overlapping a single position in a .ase.bam."""
    region = f"{chrom}:{pos}-{pos}"
    try:
        result = subprocess.run(
            [SAMTOOLS, 'view', '-c', bam_path, region],
            capture_output=True, text=True, timeout=10
        )
        return int(result.stdout.strip()) if result.returncode == 0 else 0
    except Exception:
        return 0


def fetch_sequence(chrom, start, end):
    """Fetch genomic sequence from hg38 reference."""
    try:
        result = subprocess.run(
            [SAMTOOLS, 'faidx', HG38_REF, f"{chrom}:{start}-{end}"],
            capture_output=True, text=True, timeout=10
        )
        if result.returncode != 0:
            return ''
        return ''.join(result.stdout.strip().split('\n')[1:]).upper()
    except Exception:
        return ''


def load_variants(gene, cfg):
    """Load variants from the correct aligned CSV file."""
    path = os.path.join(BASE, cfg['variant_file'])
    variants = []
    with open(path) as f:
        reader = csv.DictReader(f)
        for row in reader:
            if cfg['has_gene_col'] and row.get('gene') != cfg['gene_filter']:
                continue
            variants.append({
                'hap1_pos_rel': int(row[cfg['col_hap1_pos']]),
                'hap2_pos_rel': int(row[cfg['col_hap2_pos']]),
                'hap1_rel':     int(row[cfg['col_hap1_rel']]),
                'hap1_base':    row[cfg['col_hap1_base']],
                'hap2_base':    row[cfg['col_hap2_base']],
                'type':         row[cfg['col_type']],
            })
    return variants


def main():
    fieldnames = [
        'gene', 'hap1_chrom', 'hap1_abs_pos', 'hap2_chrom', 'hap2_abs_pos',
        'hap1_rel_to_tss',
        'hap1_base', 'hap2_base', 'variant_type', 'in_gene_body',
        # Per-cell-type ASE reads from .ase.bam (UCSC)
        'astro_hap1_reads', 'astro_hap2_reads',
        'iPSC_hap1_reads', 'iPSC_hap2_reads',
        'FPP_hap1_reads', 'FPP_hap2_reads',
        'micro_hap1_reads', 'micro_hap2_reads',
        # Evo2 sequences (from hg38 — approximate position)
        'ref_seq', 'alt_seq',
    ]

    all_rows = []

    for gene, cfg in GENES_CONFIG.items():
        print(f"\n{'='*60}")
        print(f"Processing {gene} ...")

        variants = load_variants(gene, cfg)
        print(f"  Loaded {len(variants)} variants from {cfg['variant_file']}")

        h1_chrom = cfg['hap1_chrom']
        h2_chrom = cfg['hap2_chrom']
        h1_start = cfg['fasta_start_hap1']
        h2_start = cfg['fasta_start_hap2']
        gb_h1 = cfg['gene_body_hap1']
        gb_h2 = cfg['gene_body_hap2']

        for vi, v in enumerate(variants):
            if (vi + 1) % 200 == 0:
                print(f"    {vi+1}/{len(variants)} ...")

            # Absolute haplotype coordinates
            h1_abs = h1_start + v['hap1_pos_rel']
            h2_abs = h2_start + v['hap2_pos_rel']

            # In gene body?
            in_body = (gb_h1[0] <= h1_abs <= gb_h1[1]) or \
                      (gb_h2[0] <= h2_abs <= gb_h2[1])

            # Count reads from .ase.bam at native haplotype coordinates
            counts = {}
            for ct in CELLTYPES:
                h1c = count_reads_at_pos(ase_bam('hap1', ct), h1_chrom, h1_abs)
                h2c = count_reads_at_pos(ase_bam('hap2', ct), h2_chrom, h2_abs)
                counts[ct] = (h1c, h2c)

            # Evo2 sequences: use hg38 approximate position
            # For hap1-ref allele, hap2 carries alt
            # Use hap1 absolute position mapped roughly to hg38
            # This is approximate — for Evo2 the ±512bp context matters more than exact position
            ref_seq, alt_seq = '', ''
            h1_base = v['hap1_base'].upper()
            h2_base = v['hap2_base'].upper()
            vtype = v['type']

            if vtype == 'SNV' and len(h1_base) == 1 and len(h2_base) == 1:
                # For SNVs: fetch from hg38 at approximate position, substitute
                # Use hap1 reference as "ref", hap2 as "alt"
                approx_hg38_pos = h1_abs  # approximate
                start = max(1, approx_hg38_pos - FLANK)
                end = approx_hg38_pos + FLANK
                # Fetch from hap1 reference directly
                hap1_ref = cfg['hap1_chrom'].split('_')[0]  # e.g. chr4
                # Actually fetch from the haplotype FASTA
                try:
                    result = subprocess.run(
                        [SAMTOOLS, 'faidx',
                         os.path.join(BASE, 'genomes/t2t_h9_v01_hap1.fa'),
                         f"{h1_chrom}:{h1_abs-FLANK}-{h1_abs+FLANK}"],
                        capture_output=True, text=True, timeout=10
                    )
                    if result.returncode == 0:
                        lines = result.stdout.strip().split('\n')
                        ref_seq = ''.join(lines[1:]).upper()
                        # Make alt_seq by substituting the variant base
                        offset = FLANK  # variant is at center
                        alt_seq = ref_seq[:offset] + h2_base + ref_seq[offset+1:]
                except Exception:
                    pass

            row = {
                'gene':              gene,
                'hap1_chrom':        h1_chrom,
                'hap1_abs_pos':      h1_abs,
                'hap2_chrom':        h2_chrom,
                'hap2_abs_pos':      h2_abs,
                'hap1_rel_to_tss':   v['hap1_rel'],
                'hap1_base':         h1_base,
                'hap2_base':         h2_base,
                'variant_type':      vtype,
                'in_gene_body':      str(in_body),
                'astro_hap1_reads':  counts['astrocyte'][0],
                'astro_hap2_reads':  counts['astrocyte'][1],
                'iPSC_hap1_reads':   counts['iPSC'][0],
                'iPSC_hap2_reads':   counts['iPSC'][1],
                'FPP_hap1_reads':    counts['FPP'][0],
                'FPP_hap2_reads':    counts['FPP'][1],
                'micro_hap1_reads':  counts['microglia'][0],
                'micro_hap2_reads':  counts['microglia'][1],
                'ref_seq':           ref_seq,
                'alt_seq':           alt_seq,
            }
            all_rows.append(row)

        # Gene summary
        gene_rows = [r for r in all_rows if r['gene'] == gene]
        in_body = [r for r in gene_rows if r['in_gene_body'] == 'True']
        with_astro = [r for r in gene_rows
                      if r['astro_hap1_reads'] + r['astro_hap2_reads'] > 0]

        print(f"\n  {gene} summary:")
        print(f"    Total variants:   {len(gene_rows)}")
        print(f"    In gene body:     {len(in_body)}")
        print(f"    With astro reads: {len(with_astro)}")

        # Per-cell-type gene-body totals (for verification)
        for ct in CELLTYPES:
            h1_key = f'{ct}_hap1_reads' if ct != 'microglia' else 'micro_hap1_reads'
            h2_key = f'{ct}_hap2_reads' if ct != 'microglia' else 'micro_hap2_reads'
            if ct == 'astrocyte':
                h1_key, h2_key = 'astro_hap1_reads', 'astro_hap2_reads'
            elif ct == 'iPSC':
                h1_key, h2_key = 'iPSC_hap1_reads', 'iPSC_hap2_reads'
            elif ct == 'FPP':
                h1_key, h2_key = 'FPP_hap1_reads', 'FPP_hap2_reads'

            body_h1 = sum(r[h1_key] for r in in_body)
            body_h2 = sum(r[h2_key] for r in in_body)
            fig_h1, fig_h2 = FIGURE_COUNTS[gene][ct]
            print(f"    {ct:12s}  body_sum H1={body_h1:5d} H2={body_h2:5d}  |  "
                  f"figure H1={fig_h1:4d} H2={fig_h2:4d}  "
                  f"(per-variant sums differ from gene-level counts)")

    # Write output
    with open(OUT_CSV, 'w', newline='') as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(all_rows)

    print(f"\n{'='*60}")
    print(f"Wrote {len(all_rows)} variants to {OUT_CSV}")
    print(f"  SNCA:  {sum(1 for r in all_rows if r['gene']=='SNCA')}")
    print(f"  HTT:   {sum(1 for r in all_rows if r['gene']=='HTT')}")
    print(f"  LRRK2: {sum(1 for r in all_rows if r['gene']=='LRRK2')}")
    print(f"  GBA:   {sum(1 for r in all_rows if r['gene']=='GBA')}")
    print(f"  SMN1:  {sum(1 for r in all_rows if r['gene']=='SMN1')}")


if __name__ == '__main__':
    main()
